/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package evaluator;

import jess.Userfunction;
import seakers.orekit.util.OrekitConfig;
import vassar.GlobalScope;
import vassar.VassarClient;
import vassar.database.DatabaseClient;
import vassar.database.service.DebugAPI;
import vassar.database.service.QueryAPI;
import vassar.jess.Resource;
import vassar.jess.Requests;
import vassar.jess.func.Improve;
import vassar.jess.func.SameOrBetter;
import vassar.jess.func.Worsen;
import sqs.Consumer;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.auth.credentials.EnvironmentVariableCredentialsProvider;


import java.util.*;
import java.util.concurrent.SynchronousQueue;
import java.util.concurrent.TimeUnit;
public class EvaluatorApp {

    public static void main(String[] args) {

//  _____ _   _ _____ _______
// |_   _| \ | |_   _|__   __|
//   | | |  \| | | |    | |
//   | | | . ` | | |    | |
//  _| |_| |\  |_| |_   | |
// |_____|_| \_|_____|  |_|
//

        String coverageDatabase = ResourcePaths.resourcesRootDir + "/orekit/CoverageDatabase";
        String orekitInit       = ResourcePaths.resourcesRootDir + "/orekit";

        System.setProperty("orekit.coveragedatabase", coverageDatabase);
        OrekitConfig.init(1, orekitInit);

        GlobalScope.measurementsToSubobjectives = new HashMap<>();
        GlobalScope.subobjectivesToMeasurements = new HashMap<>();

        String outputFilePath     = ResourcePaths.rootDirectory + "/debug/dbOutput.json";
        String outputPath         = ResourcePaths.rootDirectory + "/debug";

        String queueUrl           = System.getenv("EVAL_QUEUE_URL");
        String apolloUrl          = System.getenv("APOLLO_URL");
        String apolloWsUrl        = System.getenv("APOLLO_URL_WS");

        boolean debug = true;

        ArrayList<Userfunction> userFuncs = new ArrayList<>() {{
            add( new SameOrBetter() );
            add( new Improve() );
            add( new Worsen() );
        }};

        // -----> JESS REQUESTS
        String jessGlobalTempPath = ResourcePaths.resourcesRootDir + "/vassar/templates";
        String jessGlobalFuncPath = ResourcePaths.resourcesRootDir + "/vassar/functions";
        String jessAppPath        = ResourcePaths.resourcesRootDir + "/vassar/problems/SMAP/clp";
        String requestMode        = System.getenv("REQUEST_MODE");

        Requests requests = new Requests.Builder()
                                        .setGlobalTemplatePath(jessGlobalTempPath)
                                        .setGlobalFunctionPath(jessGlobalFuncPath)
                                        .setFunctionTemplates()
                                        .setRequestMode(requestMode)
                                        .setJessAppPath(jessAppPath)
                                        .build();


        // -----> When scaling, private queue names will be random
        SynchronousQueue<Map<String, String>> queue = new SynchronousQueue<>();

        System.out.println("\n------------------ VASSAR INIT ------------------");
        System.out.println("----------> APOLLO URL: " + apolloUrl);
        System.out.println("-----> INPUT QUEUE URL: " + queueUrl);
        System.out.println("--------> REQUEST MODE: " + requestMode);
        System.out.println("-------------------------------------------------------\n");


//  _           _ _     _
// | |         (_) |   | |
// | |__  _   _ _| | __| |
// | '_ \| | | | | |/ _` |
// | |_) | |_| | | | (_| |
// |_.__/ \__,_|_|_|\__,_|
//


        // --> SQS
        final SqsClient sqsClient = SqsClient.builder()
                                       .region(Region.US_EAST_2)
                                       .credentialsProvider(EnvironmentVariableCredentialsProvider.create())
                                       .build();


        QueryAPI queryAPI = new QueryAPI.Builder(apolloUrl, apolloWsUrl)
                                        .privateQueue(queue)
                                        .sqsClient(sqsClient)
                                        .build();

        DebugAPI debugAPI = new DebugAPI.Builder(outputFilePath)
                                        .newFile()
                                        .setOutputPath(outputPath)
                                        .build();

        DatabaseClient dbClient = new DatabaseClient.Builder()
                                        .debug(debug)
                                        .queryClient(queryAPI)
                                        .debugClient(debugAPI)
                                        .subscribe()
                                        .build();

        Resource engine = new Resource.Builder(dbClient)
                                        .addUserFunctionBatch(userFuncs)      // - Improve(), SameOrBetter(), Worsen()
                                        .setRequests(requests.getRequests())  // - eval: template requests (+ functions)
                                        .setRequestMode(requestMode)
                                        .build();

        VassarClient vClient = new VassarClient.Builder()
                                        .setEngine(engine)
                                        .build();

        Consumer evaluator = new Consumer.Builder(sqsClient)
                                         .setVassarClient(vClient)
                                         .setQueueUrl(queueUrl)
                                         .setPrivateQueue(queue)
                                         .debug(debug)
                                         .build();

        // RUN CONSUMER
        evaluator.run();
    }

    // ---> SLEEP
    public static void sleep(int seconds){
        try                            { TimeUnit.SECONDS.sleep(seconds); }
        catch (InterruptedException e) { e.printStackTrace(); }
    }

}
