/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package evaluator;

import jess.Userfunction;
import okhttp3.OkHttpClient;
import seakers.orekit.util.OrekitConfig;
import software.amazon.awssdk.services.ec2.Ec2Client;
import vassar.GlobalScope;
import vassar.VassarClient;
import vassar.database.DatabaseClient;
import vassar.database.service.DebugAPI;
import vassar.database.service.QueryAPI;
import vassar.jess.Resource;
import vassar.jess.Requests;
import vassar.jess.func.Improve;
import vassar.jess.func.SameOrBetter;
import vassar.jess.func.Worsen;
import sqs.Consumer;
import software.amazon.awssdk.services.ecs.EcsClient;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.SqsClientBuilder;
import software.amazon.awssdk.regions.Region;

import java.net.URI;
import java.util.*;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.TimeUnit;
import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;

public class EvaluatorApp {

    public static void main(String[] args) {

//  _____ _   _ _____ _______
// |_   _| \ | |_   _|__   __|
//   | | |  \| | | |    | |
//   | | | . ` | | |    | |
//  _| |_| |\  |_| |_   | |
// |_____|_| \_|_____|  |_|
//
        String coverageDatabase = ResourcePaths.resourcesRootDir + "/orekit/CoverageDatabase";
        String orekitInit       = ResourcePaths.resourcesRootDir + "/orekit";

        System.setProperty("orekit.coveragedatabase", coverageDatabase);
        OrekitConfig.init(1, orekitInit);

        GlobalScope.measurementsToSubobjectives = new HashMap<>();
        GlobalScope.subobjectivesToMeasurements = new HashMap<>();

        String outputFilePath     = ResourcePaths.rootDirectory + "/debug/dbOutput.json";
        String outputPath         = ResourcePaths.rootDirectory + "/debug";

        String region             = System.getenv("REGION");
        String requestQueueUrl    = System.getenv("EVAL_REQUEST_URL");
        String responseQueueUrl   = System.getenv("EVAL_RESPONSE_URL");
        String apolloUrl          = System.getenv("APOLLO_URL");
        String apolloWsUrl        = System.getenv("APOLLO_URL_WS");

        boolean debug = true;

        ArrayList<Userfunction> userFuncs = new ArrayList<>() {{
            add( new SameOrBetter() );
            add( new Improve() );
            add( new Worsen() );
        }};

        // -----> JESS REQUESTS
        String jessGlobalTempPath = ResourcePaths.resourcesRootDir + "/vassar/templates";
        String jessGlobalFuncPath = ResourcePaths.resourcesRootDir + "/vassar/functions";
        String jessAppPath        = ResourcePaths.resourcesRootDir + "/vassar/problems/SMAP/clp";
        String requestMode        = System.getenv("REQUEST_MODE");

        


        // -----> When scaling, private queue names will be random
        ConcurrentLinkedQueue<Map<String, String>> queue = new ConcurrentLinkedQueue<>();

        System.out.println("\n------------------ VASSAR INIT ------------------");
        System.out.println("--------------> APOLLO URL: " + apolloUrl);
        System.out.println("------> EVAL REQUEST QUEUE: " + requestQueueUrl);
        System.out.println("-----> EVAL RESPONSE QUEUE: " + responseQueueUrl);
        System.out.println("------> PING REQUEST QUEUE: " + System.getenv("PING_REQUEST_URL"));
        System.out.println("-----> PING RESPONSE QUEUE: " + System.getenv("PING_RESPONSE_URL"));
        System.out.println("------> PRIV REQUEST QUEUE: " + System.getenv("PRIVATE_REQUEST_URL"));
        System.out.println("-----> PRIV RESPONSE QUEUE: " + System.getenv("PRIVATE_RESPONSE_URL"));
        System.out.println("------------> REQUEST MODE: " + requestMode);
        System.out.println("--------> DEVELOPMENT TYPE: " + System.getenv("DEPLOYMENT_TYPE"));
        System.out.println("-------------------------------------------------------\n");


        Requests requests = new Requests.Builder()
                                        .setGlobalTemplatePath(jessGlobalTempPath)
                                        .setGlobalFunctionPath(jessGlobalFuncPath)
                                        .setFunctionTemplates()
                                        .setRequestMode(requestMode)
                                        .setJessAppPath(jessAppPath)
                                        .build();


//  _           _ _     _
// | |         (_) |   | |
// | |__  _   _ _| | __| |
// | '_ \| | | | | |/ _` |
// | |_) | |_| | | | (_| |
// |_.__/ \__,_|_|_|\__,_|
//
        
        // --> SQS Client
        SqsClientBuilder sqsClientBuilder = SqsClient.builder().region(Region.US_EAST_2);

        final SqsClient sqsClient = sqsClientBuilder.build();

        // --> ECS Client
        EcsClient ecsClient = EcsClient.builder()
                .region(Region.US_EAST_2)
                .build();

        // --> EC2 Client
        Ec2Client ec2Client = Ec2Client.builder()
                .region(Region.US_EAST_2)
                .build();

        // --> APIs
        QueryAPI queryAPI = new QueryAPI.Builder(apolloUrl, apolloWsUrl)
                                        .privateQueue(queue)
                                        .sqsClient(sqsClient)
                                        .build();

        DebugAPI debugAPI = new DebugAPI.Builder(outputFilePath)
                                        .setOutputPath(outputPath)
                                        .newFile()
                                        .build();

        DatabaseClient dbClient = new DatabaseClient.Builder()
                                        .debug(debug)
                                        .queryClient(queryAPI)
                                        .debugClient(debugAPI)
                                        .subscribe()
                                        .build();

        Resource engine = new Resource.Builder(dbClient)
                                        .addUserFunctionBatch(userFuncs)      // - Improve(), SameOrBetter(), Worsen()
                                        .setRequests(requests.getRequests())  // - eval: template requests (+ functions)
                                        .setRequestMode(requestMode)
                                        .build();

        VassarClient vClient = new VassarClient.Builder()
                                        .setEngine(engine)
                                        .build();
        


        Consumer evaluator = new Consumer.Builder(sqsClient)
                                         .setVassarClient(vClient)
                                         .setRequestQueueUrl(requestQueueUrl)
                                         .setResponseQueueUrl(responseQueueUrl)
                                         .setPrivateQueue(queue)
                                         .setECSClient(ecsClient)
                                         .setEC2Client(ec2Client)
                                         .debug(debug)
                                         .build();// RUN CONSUMER
        try {
            evaluator.run();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        finally {
            sqsClient.close();
            queryAPI.cancelAllSubscriptions();
            if (ecsClient != null) {
                ecsClient.close();
            }
            OrekitConfig.end();
            System.exit(0);
        }
    }

    // ---> SLEEP
    public static void sleep(int seconds){
        try                            { TimeUnit.SECONDS.sleep(seconds); }
        catch (InterruptedException e) { e.printStackTrace(); }
    }
}
